ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/B97/NAM_merged_ec_reads_mapped_to_B73.bam B97.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML103/NAM_merged_ec_reads_mapped_to_B73.bam CML103.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/B73/NAM_merged_ec_reads_mapped_to_B73.bam B73.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML277/NAM_merged_ec_reads_mapped_to_B73.bam CML277.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Oh7b/NAM_merged_ec_reads_mapped_to_B73.bam Oh7b.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/HP301/NAM_merged_ec_reads_mapped_to_B73.bam HP301.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/NC350/NAM_merged_ec_reads_mapped_to_B73.bam NC350.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/IL14/NAM_merged_ec_reads_mapped_to_B73.bam IL14.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML228/NAM_merged_ec_reads_mapped_to_B73.bam CML228.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Ki11/NAM_merged_ec_reads_mapped_to_B73.bam Ki11.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML322/NAM_merged_ec_reads_mapped_to_B73.bam CML322.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/B73_Ab10/NAM_merged_ec_reads_mapped_to_B73.bam B73_Ab10.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/P39/NAM_merged_ec_reads_mapped_to_B73.bam P39.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Ky21/NAM_merged_ec_reads_mapped_to_B73.bam Ky21.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Oh43/NAM_merged_ec_reads_mapped_to_B73.bam Oh43.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Mo18W/NAM_merged_ec_reads_mapped_to_B73.bam Mo18W.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/MS71/NAM_merged_ec_reads_mapped_to_B73.bam MS71.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML333/NAM_merged_ec_reads_mapped_to_B73.bam CML333.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML69/NAM_merged_ec_reads_mapped_to_B73.bam CML69.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Ki3/NAM_merged_ec_reads_mapped_to_B73.bam Ki3.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Tx303/NAM_merged_ec_reads_mapped_to_B73.bam Tx303.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML52/NAM_merged_ec_reads_mapped_to_B73.bam CML52.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/M162W/NAM_merged_ec_reads_mapped_to_B73.bam M162W.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/NC358/NAM_merged_ec_reads_mapped_to_B73.bam NC358.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/Tzi8/NAM_merged_ec_reads_mapped_to_B73.bam Tzi8.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/M37W/NAM_merged_ec_reads_mapped_to_B73.bam M37W.bam
ln -s /work/LAS/mhufford-lab/arnstrm/newNAM/analyses/a-corrected-reads-mapping/CML247/NAM_merged_ec_reads_mapped_to_B73.bam CML247.bam
