#!/bin/bash
rm *mapped_onemap-cM.agp
rm *mapped_onemap-cM.bed
rm *mapped_onemap-cM.chain
rm *mapped_onemap-cM.chr.agp
rm *mapped_onemap-cM.chr.fasta
rm *mapped_onemap-cM.csv
rm *mapped_onemap-cM.fasta
rm *mapped_onemap-cM.fasta.sizes
rm *mapped_onemap-cM.lifted.bed
rm *mapped_onemap-cM.summary.txt
rm *mapped_onemap-cM.tour
rm *mapped_onemap-cM.unplaced.agp
rm *mapped_onemap-cM.unplaced.fasta
rm *markers.fasta
rm *markers_mapped.bam
rm *markers_mapped.sam
rm *markers_mapped_sorted.bam
rm *markers_part1.txt
rm *markers_part2.txt
rm *onemap-cM.csv
rm chr1.pdf
rm chr2.pdf
rm chr3.pdf
rm chr4.pdf
rm chr5.pdf
rm chr6.pdf
rm chr7.pdf
rm chr8.pdf
rm chr9.pdf
rm chr10.pdf
rm mapping_stats.txt
rm markers_locations_distance.bed
rm marker_distnace.txt
rm marker_locations.txt
rm results_onemap_chr1.csv
rm results_onemap_chr1_right.csv
rm results_onemap_chr2.csv
rm results_onemap_chr2_right.csv
rm results_onemap_chr3.csv
rm results_onemap_chr3_right.csv
rm results_onemap_chr4.csv
rm results_onemap_chr4_right.csv
rm results_onemap_chr5.csv
rm results_onemap_chr5_right.csv
rm results_onemap_chr6.csv
rm results_onemap_chr6_right.csv
rm results_onemap_chr7.csv
rm results_onemap_chr7_right.csv
rm results_onemap_chr8.csv
rm results_onemap_chr8_right.csv
rm results_onemap_chr9.csv
rm results_onemap_chr9_right.csv
rm results_onemap_chr10.csv
rm results_onemap_chr10_right.csv
rm -rf tsp_work
rm unmapped
rm weights.txt
