#!/bin/bash
if [ "$#" -ne 2 ] ; then
echo "please provide:"
echo -e "\t\t(1) AGP file generated by ALLMAPS"
echo -e "\t\t(2) Scaffolds in FASTA format"
echo "";
echo "make-chr-from-agp.sh <agpfile> <scaffolds>" ;
echo "";
exit 0;
fi
agp="$1"
scaf="$2"
nam=$(basename $scaf |cut -f 1 -d ".")
python -m jcvi.formats.agp build $agp $scaf ${nam}.pseudomolecules-v2.fasta
