#!/bin/bash
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/B73_AB10.scaffolds.fasta B73_AB10/B73_AB10_index/B73_AB10.scaffolds.fasta
#ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/B73.scaffolds.fasta B73/B73_index/B73.scaffolds.fasta
#ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/B97.scaffolds.fasta B97/B97_index/B97.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML228.scaffolds.fasta CML228/CML228_index/CML228.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML247.scaffolds.fasta CML247/CML247_index/CML247.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML277.scaffolds.fasta CML277/CML277_index/CML277.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML322.scaffolds.fasta CML322/CML322_index/CML322.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML52.scaffolds.fasta CML52/CML52_index/CML52.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/CML69.scaffolds.fasta CML69/CML69_index/CML69.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/HP301.scaffolds.fasta HP301/HP301_index/HP301.scaffolds.fasta
#ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/IL14H.scaffolds.fasta IL14H/IL14H_index/IL14H.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Ki11.scaffolds.fasta Ki11/Ki11_index/Ki11.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Ki3.scaffolds.fasta Ki3/Ki3_index/Ki3.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Ky21.scaffolds.fasta Ky21/Ky21_index/Ky21.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/M162W.scaffolds.fasta M162W/M162W_index/M162W.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/M37W.scaffolds.fasta M37W/M37W_index/M37W.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Mo18W.scaffolds.fasta Mo18W/Mo18W_index/Mo18W.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/MS71.scaffolds.fasta MS71/MS71_index/MS71.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/NC350.scaffolds.fasta NC350/NC350_index/NC350.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/NC358.scaffolds.fasta NC358/NC358_index/NC358.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Oh43.scaffolds.fasta Oh43/Oh43_index/Oh43.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Oh7b.scaffolds.fasta Oh7b/Oh7b_index/Oh7b.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/P39.scaffolds.fasta P39/P39_index/P39.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Tx303.scaffolds.fasta Tx303/Tx303_index/Tx303.scaffolds.fasta
ln -s /work/LAS/mhufford-lab/arnstrm/NAM_Canu1.8/scaffolds/Tzi8.scaffolds.fasta Tzi8/Tzi8_index/Tzi8.scaffolds.fasta
